### ISSUE TITLE
Panic due to unwrap of None on src/schedule_graph/mod.rs:596

### ISSUE THREAD

**Issue by thefakeplace** [jakobhellermann/bevy_mod_debugdump#18]
Happened between my last two project's commits, was using this fine before.

Full stack trace:
```
panicked at 'called `Option::unwrap()` on a `None` value', /Users/tfp/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_mod_debugdump-0.7.0/src/schedule_graph/mod.rs:596:27

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (http://localhost:8770/api/wasm.js:378:13)
    at __wbg_new_abda76e883ba8a5f externref shim (http://localhost:8770/api/wasm.wasm:wasm-function[40185]:0x11657c3)
    at console_error_panic_hook::hook::h87c767ff6c9aa7f7 (http://localhost:8770/api/wasm.wasm:wasm-function[11437]:0xccc55b)
    at core::ops::function::Fn::call::h97e0e8b91e1d35b5 (http://localhost:8770/api/wasm.wasm:wasm-function[55099]:0x11a5f23)
    at std::panicking::rust_panic_with_hook::h00df10c1b877177e (http://localhost:8770/api/wasm.wasm:wasm-function[19386]:0xf42803)
    at std::panicking::begin_panic_handler::{{closure}}::h18050073fecbd1cc (http://localhost:8770/api/wasm.wasm:wasm-function[22296]:0xfcc29e)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ab0e48305983289 (http://localhost:8770/api/wasm.wasm:wasm-function[35944]:0x11437b4)
    at rust_begin_unwind (http://localhost:8770/api/wasm.wasm:wasm-function[30350]:0x10e0463)
    at core::panicking::panic_fmt::h4371046c91cc0cbc (http://localhost:8770/api/wasm.wasm:wasm-function[34308]:0x112c984)
    at core::panicking::panic::h9782141a857ffa9c (http://localhost:8770/api/wasm.wasm:wasm-function[31277]:0x10f4f28)
```

I'm not sure how to get a better trace-- using WASM in release mode with `debug = true` set for the release profile in `Cargo.toml`.

This happens when dumping like this:

```rust
 let core_graph_dot = bevy_mod_debugdump::schedule_graph_dot(app,
     CoreSchedule::Main,
     &bevy_mod_debugdump::schedule_graph::Settings::default());
```

My schedule is too complex to put here, so maybe I can try to make a minimal case to replicate with if this isn't enough.

**Comment by Shatur** [comment]
I have the same problem on 0.8:
```
/home/gena/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_debugdump-0.8.0/src/schedule_graph/mod.rs|601 col 14| called `Option::unwrap()` on a `None` value
|| stack backtrace:
||    0: rust_begin_unwind
||              at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
||    1: core::panicking::panic_fmt
||              at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
||    2: core::panicking::panic
||              at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:117:5
||    3: core::option::Option<T>::unwrap
||              at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/option.rs:935:21
||    4: bevy_mod_debugdump::schedule_graph::ScheduleGraphContext::system_of_system_type
||              at /home/gena/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_debugdump-0.8.0/src/schedule_graph/mod.rs:597:27
||    5: bevy_mod_debugdump::schedule_graph::ScheduleGraphContext::node_ref
||              at /home/gena/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_debugdump-0.8.0/src/schedule_graph/mod.rs:621:39
||    6: bevy_mod_debugdump::schedule_graph::ScheduleGraphContext::add_dependencies
||              at /home/gena/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_debugdump-0.8.0/src/schedule_graph/mod.rs:248:18
||    7: bevy_mod_debugdump::schedule_graph::schedule_graph_dot
||              at /home/gena/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_debugdump-0.8.0/src/schedule_graph/mod.rs:163:5
||    8: bevy_mod_debugdump::schedule_graph_dot::schedule_graph_dot_inner::{{closure}}
||              at /home/gena/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_debugdump-0.8.0/src/lib.rs:31:17
||    9: bevy_ecs::world::World::resource_scope
||              at /home/gena/.cargo/git/checkouts/bevy-f7ffde730c324c74/c71ae26/crates/bevy_ecs/src/world/mod.rs:1344:22
||   10: bevy_mod_debugdump::schedule_graph_dot::schedule_graph_dot_inner
||              at /home/gena/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_debugdump-0.8.0/src/lib.rs:22:9
||   11: bevy_mod_debugdump::schedule_graph_dot
||              at /home/gena/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_debugdump-0.8.0/src/lib.rs:35:5
||   12: bevy_mod_debugdump::print_schedule_graph
||              at /home/gena/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_debugdump-0.8.0/src/lib.rs:40:15
||   13: lifescape::main
||              at ./src/main.rs:85:5
||   14: core::ops::function::FnOnce::call_once
||              at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
```

**Comment by rparrett** [comment]
I am seeing this as well, but only when dumping a particular schedule. Don't have a minimal repro, but in case it's useful, here's a commit that reproduces the issue.  https://github.com/rparrett/undefended/commit/f325fefaa5336ee66a92fba5d773d42c24a6383e

**Comment by rparrett** [comment]
Actually, here's a much more minimal reproducer:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index a929bb8..c48c8a1 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -25,6 +25,7 @@ once_cell = "1.17"
 
 [dev-dependencies]
 bevy = "0.11"
+bevy_rapier3d = "0.22"
 
 [[example]]
 name = "print_render_graph"
diff --git a/examples/print_schedule_graph.rs b/examples/print_schedule_graph.rs
index 144bc9d..eda5398 100644
--- a/examples/print_schedule_graph.rs
+++ b/examples/print_schedule_graph.rs
@@ -1,8 +1,10 @@
 use bevy::log::LogPlugin;
 use bevy::prelude::*;
+use bevy_rapier3d::prelude::*;
 
 fn main() {
     let mut app = App::new();
     app.add_plugins(DefaultPlugins.build().disable::<LogPlugin>());
-    bevy_mod_debugdump::print_schedule_graph(&mut app, Update);
+    app.add_plugins(RapierPhysicsPlugin::<NoUserData>::default());
+    bevy_mod_debugdump::print_schedule_graph(&mut app, PostUpdate);
 }
```

**Comment by rparrett** [comment]
Okay, I think I see what is going on here.

Rapier is ordering some systems in `PostUpdate` with `.after(scene_spawner_system)`, but that system is in the `Update` schedule.

Here's a minimal repro:

```rust
use bevy::prelude::*;

fn test_system_1() {}
fn test_system_2() {}

fn main() {
    let mut app = App::new();
    app.add_systems(PostUpdate, test_system_1);
    app.add_systems(Update, test_system_2.after(test_system_1));

    bevy_mod_debugdump::print_schedule_graph(&mut app, Update);
}
```

If you're seeing this error in your own code, you might be doing something similarly silly.
